name: Comprobación TDD

on:
  push:
    branches: [ "test" ]  # Solo se ejecuta en push a la rama test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file ./codigo-app/pom.xml
    - name: Run Tests
      run: mvn test --file ./codigo-app/pom.xml

    # Solo si los tests son exitosos, realizar el merge
    - name: Merge test into main
      if: success()  # Solo se ejecuta si los pasos anteriores son exitosos
      uses: github-script@v6
      with:
        script: |
          const branchName = 'main';
          const { data: pullRequests } = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: `${context.repo.owner}:test`,
            base: branchName,
            state: 'open',
          });

          if (pullRequests.length === 0) {
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Merge test into main',
              head: 'test',
              base: 'main',
            });
            console.log(`PR creado: ${pr.html_url}`);
          } else {
            const pr = pullRequests[0];
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
            });
            console.log(`Merge realizado en el PR: ${pr.html_url}`);
          }
